### ISSUE TITLE
Issue with "Revert levels" setting

### ISSUE THREAD

**Issue by malomaster** [millerscout/MMD-Factorio-Mods#8]
When I tried to play this mod with different "max_level" number with my modpack, I found that with numbers more than 50 the game got too much impact on UPS, save loaded and saved too slow, moreover, with `max_level = 100` the game eats 25+ GB RAM -- I think it is too much for it. So after those tests I reduced "max_level" to 20. Of course, I don't wanted to lost most of my buildings, so used "Revert levels" button in runtime settings. Then, after reducing "max_level" and reloading, I turn "Revert levels" off. Entities must got levels again after this, levels must just be recalculated, I thought. But for some reason it doesn't working – machines doesn't get levels again. Even reloading the game doesn't work.
Can you add on_settings_changed check in "control.lua": if "exp_for_buildings_revert_levels" is turned off, then start replacing normal entities to leveled again?

**Comment by millerscout** [comment]
hello, 
i need more detail, which modpack, but im playing with 163 mods ( SE +K2 ).
No UPS hit yet, using 100 levels.
without my mod it  ~6GBs, and using ~8GBs
i don't know if there's a way to optimize RAM, as factorio handles that internally, i may research about what can be achieved, there's the #3 possibility, but i'm not implementing this mod as module in the near future

there's no need to implement the revert_levels turned off, because [it's implemented.](https://github.com/millerscout/MMD-Factorio-Mods/blob/main/xp-for-buildings/control.lua#L635)
what may happen is max-levels [aren't updated ](https://github.com/millerscout/MMD-Factorio-Mods/blob/main/xp-for-buildings/control.lua#L620)in-game (that's a bug) 

the workaround is, change your max_level at startup, and to reset the machines change the baseExp to baseExp +1
it should trigger the update for every machine again.

**Comment by malomaster** [comment]
[Here](https://github.com/millerscout/MMD-Factorio-Mods/issues/1#issuecomment-1751604296) I have already written list of mods I'm using now, also there is a link to all modified mods and list of most (if not all) my modifications except two deleted strings I mentioned [here](https://github.com/millerscout/MMD-Factorio-Mods/issues/1#issuecomment-1761174275).
If you wanted, I can upload mod-list and mod-settings.

And… I think I found the issue. The thing is, when you add your mod to an existing game or turn on and off "Revert levels" setting, I think, the script does not update all machines immediately, because it is triggered only when an entity got xp for the next level. So, if you write large numbers to mod runtime settings (like "1440;100;100;5;1.5" I used now -- with those numbers entity need to produce a little over 1mil items to got max_level (20)) and entity have high xp values, entity update does not be triggered until it got xp required for the next level.
By the way, "factory-levels" doesn't have this issue – all entities become updated when they produce the first item after the mod was turned on. I think it has some additional check.

I was wrong. Apparently I got some strange bug somewhere in the chain: transition from "Factory levels" to "XP-for-building", when I used FL's "Revert levels" -- increasing max_level to 100 -- turning on XPfB's "Revert levels" -- decreasing max_level to 20 -- changing numbers in XPfB's settings to "1440;100;100;5;1.5" -- turning off XPfB's "Revert levels" -- editing numbers again for re-triggering entities update.
For some reason, levels are triggered only for new buildings or for deleted and then placed back (for example, by pressing [Ctrl+Z]). Interestingly, entities deleted and placed back got wrong levels -- for example, they can get max_level (20), when they made only 10-20k items when 20th level need a little over 1 mil items, what I wrote above.

**Comment by millerscout** [comment]
there's alot of thing to read 😆  i'm trying my best

i've added your changes

btw you may fork and make changes and send a PR it'll be easier for both of us 😉 

i'm adding disco science compatibility

**Comment by millerscout** [comment]
0.0.29 done
it's discoscience compatible

**Comment by millerscout** [comment]
> And… I think I found the issue. The thing is, when you add your mod to an existing game or turn on and off "Revert levels" setting, I think, the script does not update all machines immediately, because it is triggered only when an entity got xp for the next level. So, if you write large numbers to mod runtime settings (like "1440;100;100;5;1.5" I used now -- with those numbers entity need to produce a little over 1mil items to got max_level (20)) and entity have high xp values, entity update does not be triggered until it got xp required for the next level. By the way, "factory-levels" doesn't have this issue – all entities become updated when they produce the first item after the mod was turned on. I think it has some additional check.
> 

it does update, not immediately because it hangs if i wrote like that, 

the code for updating factories works just like factory levels for now, i did increased how many entities are checked  
factory levels it's faster to change entities because it has a fewer types to check.


i may increase how many entities are updated , yet i don't think it's required right now, 
because i tried turn on revert_levels in a huge base from a user, and i did reverted the whole base in few seconds, 
you may try to increase [here](https://github.com/millerscout/MMD-Factorio-Mods/blob/main/xp-for-buildings/control.lua#L475) 



as for the bug 
> I was wrong. Apparently I got some strange bug somewhere in the chain: transition from "Factory levels" to "XP-for-building", when I used FL's "Revert levels" -- increasing max_level to 100 -- turning on XPfB's "Revert levels" -- decreasing max_level to 20 -- changing numbers in XPfB's settings to "1440;100;100;5;1.5" -- turning off XPfB's "Revert levels" -- editing numbers again for re-triggering entities update.
For some reason, levels are triggered only for new buildings or for deleted and then placed back (for example, by pressing [Ctrl+Z]). Interestingly, entities deleted and placed back got wrong levels -- for example, they can get max_level (20), when they made only 10-20k items when 20th level need a little over 1 mil items, what I wrote above.
>

currently when you change the max level, it doesn't update level in a new game, that's a bug.
to [properly trigger ](https://github.com/millerscout/MMD-Factorio-Mods/blob/main/xp-for-buildings/control.lua#L601)you need to change the baseExp to another value. i`ll fix it in upcoming patches.

**Comment by malomaster** [comment]
> to [properly trigger ](https://github.com/millerscout/MMD-Factorio-Mods/blob/main/xp-for-buildings/control.lua#L601)you need to change the baseExp to another value. i`ll fix it in upcoming patches.

Nope, it doesn't working. I tried to change all runtime settings, but only new buildings got XP, old entities does not gain it without deleting and rebuilding. And I have an idea why it is happened.
How do you think, is it possible that, when I transited from "Factory levels" to "XPfB" and used FL's "Revert levels", that setting was saved and, after transition, just somehow prevents to trigger already built entities' replacing? Maybe you need to add on_load checking if "factory-levels-disable-mod" setting exist and, if yes, remove this string and its value from save?

Upd.:
After some time playing I found that it triggered correctly, but for some reason it works mostly on mining drills, oil pumps etc., but almost none of assembling machines or furnaces was replaced by leveled entity.

**Comment by millerscout** [comment]
you were right all along i found the bug!

**Comment by millerscout** [comment]
just fixing right now, thanks for your pacience! and helping me narrow those pesky bugs

**Comment by malomaster** [comment]
And it is still doesn't working for assembling machines and furnaces.
